### ISSUE TITLE
test ideas

### ISSUE THREAD

**Issue by jacekkopecky** [portsoc/ws_canvas#1]
- [x] get a text string from server and put it in the page
- [x] get a simple array from server and put it in a list
- [x] get a text string from server and put it in the page, updating it every second using setInterval
- [x] give a sword to Spartacus, using the stick figure code from portsoc/Web-Canvas-Stick-Figures
- [x] cope with an XHR error, for example a request that results in a not found or forbidden
- [x] get simple coordinates and draw a triangle
- [x] get from server a simple object with coordinates and draw a box there; update the coordinates every 1s (coordinates available at http://jacek.soc.port.ac.uk/tmp/ws/dyn2 )
- [ ] get data from a server and draw a chart with the data
- [x] parallel lines
- [x] grid
- [x] czech flag (challenge: union jack)
- [ ] animate a simple bouncing box
- [ ] seascape: sky, sea, sun, seagull, ship (challenge: animated)

edit this issue to add more test ideas

**Comment by ear1grey** [comment]
Seascape in http://rjb.soc.port.ac.uk/talks/js/canvas/

**Comment by jacekkopecky** [comment]
not useful anymore
